#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# pysradb documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
#
import os
import sys

# import guzzle_sphinx_theme
import pysradb

autodoc_mock_imports = [
    "langchain_core",
    "langchain_ollama",
    "langchain_openai",
    "langgraph",
    "sentence_transformers",
    "xmltodict",
    "numpy",
    "pandas",
    "requests",
    "tqdm",
]

sys.path.insert(0, os.path.abspath(".."))


# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "IPython.sphinxext.ipython_directive",
    "IPython.sphinxext.ipython_console_highlighting",
    "sphinx.ext.mathjax",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
    "sphinx.ext.viewcode",
    "sphinx.ext.inheritance_diagram",
    "numpydoc",
    "sphinx_tabs.tabs",
    "sphinx_design",
    "sphinxcontrib.gtagjs",
    "myst_parser",
    "nbsphinx",
    "sphinx_sitemap",
]
gtagjs_ids = [
    "G-CKQZFCEENZ",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = [".rst", ".md"]
# source_suffix = ".md"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "pysradb"
copyright = "2023, Saket Choudhary"
author = "Saket Choudhary"
html_title = "pysradb: SRA, ENA, and GEO metadata search"
html_short_title = "pysradb"
html_baseurl = "https://saket-choudhary.me/pysradb/"
html_extra_path = ["robots.txt"]
html_meta = {
    "description": (
        "pysradb is a Python package and command-line tool for searching SRA, "
        "ENA, and GEO metadata, converting sequencing accessions, extracting "
        "publication identifiers, and preparing reproducible download workflows."
    ),
    "keywords": (
        "pysradb, SRA metadata, ENA metadata, GEO metadata, Sequence Read Archive, "
        "bioinformatics, genomics, RNA-seq, accession conversion, Python"
    ),
    "og:title": "pysradb: SRA, ENA, and GEO metadata search",
    "og:description": (
        "Search public sequencing metadata, convert accessions, link publications, "
        "and prepare SRA/ENA download workflows from Python or the command line."
    ),
    "og:type": "website",
    "og:url": html_baseurl,
    "twitter:card": "summary",
    "twitter:title": "pysradb",
    "twitter:description": (
        "Python and CLI tools for public sequencing metadata across SRA, ENA, and GEO."
    ),
}
# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = pysradb.__version__
# The full version, including alpha/beta/rc tags.
release = pysradb.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "light_css_variables": {
        "font-stack": "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif",
        "font-stack--monospace": "'SFMono-Regular', ui-monospace, 'Cascadia Code', 'Liberation Mono', Menlo, monospace",
        "color-brand-primary": "#007aff",
        "color-brand-content": "#0066cc",
        "color-api-name": "#1d1d1f",
        "color-api-pre-name": "#6e6e73",
        "color-background-primary": "#ffffff",
        "color-background-secondary": "#f5f5f7",
        "color-background-hover": "#f2f2f7",
        "color-code-background": "#f5f5f7",
        "color-inline-code-background": "#f2f2f7",
        "color-sidebar-background": "#fbfbfd",
        "color-sidebar-background-border": "#d2d2d7",
        "color-toc-background": "#ffffff",
        "color-toc-background-border": "#d2d2d7",
        "color-admonition-background": "#f5f5f7",
        "color-admonition-title-background": "#e8f2ff",
    },
    "dark_css_variables": {
        "font-stack": "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif",
        "font-stack--monospace": "'SFMono-Regular', ui-monospace, 'Cascadia Code', 'Liberation Mono', Menlo, monospace",
        "color-brand-primary": "#0a84ff",
        "color-brand-content": "#409cff",
        "color-api-name": "#f5f5f7",
        "color-api-pre-name": "#a1a1a6",
        "color-background-primary": "#1d1d1f",
        "color-background-secondary": "#2c2c2e",
        "color-background-hover": "#3a3a3c",
        "color-code-background": "#2c2c2e",
        "color-inline-code-background": "#3a3a3c",
        "color-sidebar-background": "#161617",
        "color-sidebar-background-border": "#38383a",
        "color-toc-background": "#1d1d1f",
        "color-toc-background-border": "#38383a",
        "color-admonition-background": "#2c2c2e",
        "color-admonition-title-background": "#06345f",
    },
    "source_repository": "https://github.com/saketkc/pysradb/",
    "source_branch": "develop",
    "source_directory": "docs/",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]


# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "pysradbdoc"


# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto, manual, or own class]).
latex_documents = [
    (master_doc, "pysradb.tex", "pysradb Documentation", "Saket Choudhary", "manual")
]


# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "pysradb", "pysradb Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "pysradb",
        "pysradb Documentation",
        author,
        "pysradb",
        "One line description of project.",
        "Miscellaneous",
    )
]


numpydoc_show_class_members = False


##html_theme_path = guzzle_sphinx_theme.html_theme_path()
##html_theme = "guzzle_sphinx_theme"
##
### Register the theme as an extension to generate a sitemap.xml
##extensions.append("guzzle_sphinx_theme")
##
### Guzzle theme options (see theme.conf for more information)
##html_theme_options = {
##    # Set the name of the project to appear in the sidebar
##    "project_nav_name": "pysradb"
##}

scv_greatest_tag = True
scv_show_banner = True

html_logo = "_static/pysradb_v3.png"

# Load custom JavaScript for copy-to-clipboard functionality
html_js_files = [
    "copy-button.js",
]

# Load custom CSS to override Pygments background colors
html_css_files = [
    "custom.css",
]

# NBSphinx configuration
nbsphinx_execute = "always"
nbsphinx_execute_arguments = [
    "--InlineBackend.figure_formats={'svg', 'pdf'}",
]
nbsphinx_kernel_name = "python3"
nbsphinx_timeout = 900
exclude_patterns.append("**/.ipynb_checkpoints")
exclude_patterns.append("notebooks/.ipynb_checkpoints")
