on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install main dependencies
        run: pip install -r requirements.txt

      - name: Install documentation dependencies
        run: pip install -r docs/requirements.txt

      - name: Install pysradb (editable mode)
        run: pip install -e .

      - name: Run tests and generate coverage report
        run: pytest --cov --cov-branch --cov-report=xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build docs
        run: |
          cd docs
          make html