name: pull_request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8 and black
        run: |
          pip install pytest coverage pytest-cov codecov black flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          black --check .

      - name: Test only geoweb tests with pytest
        run: |
          pip install --editable .
          pytest tests/test_geoweb.py tests/test_geoweb_matrix.py
          # Optionally keep coverage if needed:
          # pytest --cov=YOUR_PACKAGE tests/test_geoweb.py tests/test_geoweb_matrix.py
          # codecov

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install main dependencies
        run: pip install -r requirements.txt pytest-cov

      - name: Install documentation dependencies
        run: pip install -r docs/requirements.txt

      - name: Install pysradb (editable mode)
        run: pip install -e .

      - name: Run only geoweb tests and generate coverage report
        run: pytest --cov --cov-branch --cov-report=xml tests/test_geoweb.py tests/test_geoweb_matrix.py

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build docs
        run: |
          cd docs
          make html